FROM ubuntu:latest
RUN apt-get update -y
RUN mkdir /WORK
COPY . /WORK/
COPY ./chromedriver /usr/bin/
RUN apt-get install wget -y
RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
WORKDIR /WORK/
RUN  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN  apt install ./google-chrome-stable_current_amd64.deb -y
RUN  pip3 install -r requirements.txt
EXPOSE 8000
ENTRYPOINT [ "/bin/bash", "start.sh" ]