# Generated by Django 2.1.15 on 2020-09-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
