# Generated by Django 2.1.15 on 2020-09-19 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_submit_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
