# Generated by Django 2.1.15 on 2020-09-19 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
