# Generated by Django 2.1.15 on 2020-09-19 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200919_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
