# Generated by Django 2.1.15 on 2020-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20200919_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='url',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
