# Generated by Django 2.1.15 on 2020-09-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200919_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=10000),
        ),
    ]
