# Generated by Django 2.1.15 on 2020-09-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200919_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='pages',
        ),
    ]
