# Generated by Django 2.1.15 on 2020-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_remove_submit_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
