# Generated by Django 2.1.15 on 2020-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20200920_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='meta',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
