# Generated by Django 2.1.15 on 2020-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20200921_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
